export const PLAYER_CONFIGS = [
  {
    id: 1,
    defaultName: 'Player 1',
    color: '#FF3B30',
    secondaryColor: '#DC2626',
    lightBg: '#FFE5E5',
    icon: 'user-astronaut',
    label: 'Red Token',
  },
  {
    id: 2,
    defaultName: 'Player 2',
    color: '#007AFF',
    secondaryColor: '#2563EB',
    lightBg: '#E5F2FF',
    icon: 'user-ninja',
    label: 'Blue Token',
  },
  {
    id: 3,
    defaultName: 'Player 3',
    color: '#34C759',
    secondaryColor: '#059669',
    lightBg: '#E8F9ED',
    icon: 'user-secret',
    label: 'Green Token',
  },
  {
    id: 4,
    defaultName: 'Player 4',
    color: '#FF9500',
    secondaryColor: '#D97706',
    lightBg: '#FFF4E5',
    icon: 'user-tie',
    label: 'Yellow Token',
  },
];

export const SPACE_TYPES = {
  ORIGIN: {
    type: 'ORIGIN',
    label: 'ORIGIN',
    subtitle: '+₹1,500 Bonus',
    bgColor: '#10B981',
    accentColor: '#047857',
    borderColor: '#059669',
    textColor: '#FFFFFF',
    iconName: 'flag-checkered',
  },
  SAFE: {
    type: 'SAFE',
    label: 'SAFE POINT',
    subtitle: 'Rest & Relax',
    bgColor: '#8B5CF6',
    accentColor: '#6D28D9',
    borderColor: '#7C3AED',
    textColor: '#FFFFFF',
    iconName: 'shield-alt',
  },
  CITY: {
    type: 'CITY',
    label: 'CITY',
    bgColor: '#FFFFFF',
    accentColor: '#0284C7',
    borderColor: '#CBD5E1',
    textColor: '#0F172A',
    iconName: 'building',
  },
  MARKET: {
    type: 'MARKET',
    label: 'MARKET',
    subtitle: 'Build House',
    bgColor: '#FFEDD5',
    accentColor: '#EA580C',
    borderColor: '#F97316',
    textColor: '#9A3412',
    iconName: 'store',
  },
  FINE: {
    type: 'FINE',
    label: 'FINE',
    subtitle: 'Pay ₹1,000',
    bgColor: '#FEE2E2',
    accentColor: '#DC2626',
    borderColor: '#EF4444',
    textColor: '#991B1B',
    iconName: 'gavel',
  },
  EMPTY: {
    type: 'EMPTY',
    label: 'SAFE SPACE',
    subtitle: 'Nothing Happens',
    bgColor: '#F1F5F9',
    accentColor: '#64748B',
    borderColor: '#CBD5E1',
    textColor: '#334155',
    iconName: 'coffee',
  },
};

export const STARTING_MONEY_OPTIONS = [5000, 10000, 15000, 20000];

export const TIMER_OPTIONS = [
  { label: 'No Limit', minutes: 0 },
  { label: '5 Mins', minutes: 5 },
  { label: '10 Mins', minutes: 10 },
  { label: '15 Mins', minutes: 15 },
  { label: '20 Mins', minutes: 20 },
  { label: '30 Mins', minutes: 30 },
];

export const GAME_COLORS = {
  background: '#F1F5F9',
  cardBg: '#FFFFFF',
  surfaceBg: '#F8FAFC',
  boardCenterBg: '#E2E8F0',
  textPrimary: '#0F172A',
  textSecondary: '#475569',
  accentGold: '#D97706',
  accentEmerald: '#10B981',
  accentRed: '#EF4444',
  borderDark: '#CBD5E1',
};
