export const PLAYER_CONFIGS = [
  {
    id: 1,
    defaultName: 'Player 1',
    color: '#EF4444',
    secondaryColor: '#B91C1C',
    lightBg: '#FEE2E2',
    icon: 'user-astronaut',
    label: 'Red Token',
  },
  {
    id: 2,
    defaultName: 'Player 2',
    color: '#3B82F6',
    secondaryColor: '#1D4ED8',
    lightBg: '#DBEAFE',
    icon: 'user-ninja',
    label: 'Blue Token',
  },
  {
    id: 3,
    defaultName: 'Player 3',
    color: '#10B981',
    secondaryColor: '#047857',
    lightBg: '#D1FAE5',
    icon: 'user-secret',
    label: 'Green Token',
  },
  {
    id: 4,
    defaultName: 'Player 4',
    color: '#F59E0B',
    secondaryColor: '#B45309',
    lightBg: '#FEF3C7',
    icon: 'user-tie',
    label: 'Yellow Token',
  },
];

export const SPACE_TYPES = {
  ORIGIN: {
    type: 'ORIGIN',
    label: 'ORIGIN',
    subtitle: '+₹1,500 Bonus',
    bgColor: '#064E3B',
    accentColor: '#10B981',
    borderColor: '#34D399',
    iconName: 'flag-checkered',
  },
  SAFE: {
    type: 'SAFE',
    label: 'SAFE POINT',
    subtitle: 'Rest & Relax',
    bgColor: '#4C1D95',
    accentColor: '#8B5CF6',
    borderColor: '#A78BFA',
    iconName: 'shield-alt',
  },
  CITY: {
    type: 'CITY',
    label: 'CITY',
    bgColor: '#1E293B',
    accentColor: '#38BDF8',
    borderColor: '#475569',
    iconName: 'building',
  },
  MARKET: {
    type: 'MARKET',
    label: 'MARKET',
    subtitle: 'Build House',
    bgColor: '#7C2D12',
    accentColor: '#F97316',
    borderColor: '#FB923C',
    iconName: 'store',
  },
  FINE: {
    type: 'FINE',
    label: 'FINE',
    subtitle: 'Pay ₹1,000',
    bgColor: '#7F1D1D',
    accentColor: '#EF4444',
    borderColor: '#F87171',
    iconName: 'gavel',
  },
  EMPTY: {
    type: 'EMPTY',
    label: 'SAFE SPACE',
    subtitle: 'Nothing Happens',
    bgColor: '#334155',
    accentColor: '#94A3B8',
    borderColor: '#64748B',
    iconName: 'coffee',
  },
};

export const STARTING_MONEY_OPTIONS = [5000, 10000, 15000, 20000];

export const GAME_COLORS = {
  background: '#0F172A',
  cardBg: '#1E293B',
  surfaceBg: '#0F172A',
  boardCenterBg: '#0F172A',
  textPrimary: '#F8FAFC',
  textSecondary: '#94A3B8',
  accentGold: '#F59E0B',
  accentEmerald: '#10B981',
  accentRed: '#EF4444',
  borderDark: '#334155',
};
